### PR TITLE
FIx/Clean Project Structure And Maven Configuration

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by TekkitCommando** [comment]
I will look at this PR in my coding hour today at school :) I gotta go or I will be late xD

**Comment by TekkitCommando** [comment]
@sgdc3 Was there a reason the updater was deleted. I haven't had a chance to look at it closely but I know it was deleted :P

**Comment by sgdc3** [comment]
I removed the updater because I remember you can add it as maven dependency.

**Comment by sgdc3** [comment]
Anyway the updater is useless in snapshot builds.

**Comment by TekkitCommando** [comment]
Hmmm Ok

**Comment by TekkitCommando** [comment]
Everything seems good so I will merge it. I will at it closer when I get home, but I don't see any problems :+1:

**Pull request merged**
